#!/usr/bin/env bash
# Transfer a file from our client to a server
if [[ $# < 3 ]]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	FILE=$1
	IP=$2
	USER=$3

	if [[ $# == 3 ]]
	then
		scp -o StrictHostKeyChecking=no $FILE "$USER@$IP:~/"
	else
		PATH_KEY=$4
		scp -i $PATH_KEY -o StrictHostKeyChecking=no $FILE "$USER@$IP:~/"
	fi
fi
