#!/usr/bin/env bash
# Installs nginx on a web server, sets content and redirect action
sudo apt-get update
sudo apt-get install nginx -y
# Sets content
echo "Holberton School" | sudo tee "/var/www/html/index.html"
# Sets permanent redirect
new_string="\\\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "/server_name _;/a $new_string" /etc/nginx/sites-available/default
sudo service nginx restart
