#!/usr/bin/env bash
# Installs and configure a load balancer on server lb-01
sudo apt update
sudo apt install haproxy -y
sudo sed -i '$ aENABLED=1' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
echo -e "\nfrontend haproxynode\nbind *:80\nmode http\ndefault_backend backendnodes\n" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "backend backendnodes\nbalance roundrobin\nserver 2367-web-01 35.227.117.239:80 check\nserver 2367-web-02 3.89.194.105:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
