#!/usr/bin/env bash
# Task 9 Process and PID file
file="/var/run/holbertonscript.pid"
echo $$ > "$file"
trap 'echo "I hate the kill command"; rm "$file"; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm "$file"; exit' SIGQUIT

while ((1))
do
	echo "To infinity and beyond"
	sleep 2
done
