#!/usr/bin/env bash
# Manages the deamon 'manage_my_process'

file="/var/run/my_process.pid"
if [[ $# -eq 1 ]]
then
	case "$1" in

		"start")
		./manage_my_process &
		echo "$!" > $file
		echo "manage_my_process started"
		;;

		"stop")
		kill "$(cat $file)"
		rm $file
		echo "manage_my_process stopped"
		;;

		"restart")
		kill "$(cat $file)"
		./manage_my_process &
		echo "$!" > $file
		echo "manage_my_process restarted"
		;;

		*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
	esac
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi

