#!/usr/bin/env bash
# Displays numbers from 1 to 100
# Requirements:
# 	Displays FizzBuzz when the number is a multiple of 3 and 5
# 	Displays Fizz when the number is multiple of 3
# 	Displays Buzz when the number is a multiple of 5
# 	Otherwise, displays the number

for i in {1..100}
do
	out=""
	if [ $((i % 3)) -eq 0 ]
	then
		out="${out}Fizz"
	fi
	if [ $((i % 5)) -eq 0 ]
	then
		out="${out}Buzz"
	fi
	if [ -z "$out" ]
	then
		out="$i"
	fi
	echo "$out"
done
