#!/usr/bin/env bash
# Displays the content of the file /etc/passwd.
# Display only: username, user id and Home directory path for the user

input="/etc/passwd"
while read -r line
do
	echo "$line" | cut -d ':' -f1,3,6
done < "$input"
