#!/usr/bin/env bash
# Supertitions numbers, loops from 1 to 20 and prints 3 bad luck messages

i=1
while [ $i -lt 21 ]
do
	echo "$i"

	case $i in

		4)
		echo "bad luck from China"
		;;

		9)
		echo "bad luck from Japan"
		;;

		17)
		echo "bad luck from Italy"
		;;

	esac
	((i++))
done
