#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes: 
# 	display hours from 0 to 12 -- display minutes from 1 to 59

hrs=0
while [ $hrs -lt 13 ]
do
	echo "Hour: $hrs"

	min=1
	while [ $min -lt 60 ]; do echo "$min"; ((min++)); done

	((hrs++))
done
