#!/usr/bin/env bash
# Displays The content of the current directory, In a list format
# Where only the part of the name after the first dash is displayed

LIST="$(ls)"
for i in $LIST; do
	echo "$i" | cut -d '-' -f 2
done
