#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user
chmod 644 /etc/nginx/nginx.conf
sed -i '1iuser nginx;' /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
pkill apache2
sudo -u nginx service nginx restart
